# @package _global_

space: T1w
use_template_gm: False
gm_path: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_label-GM_desc-from-FS_dseg.nii.gz

use_template_parcel: False
parcellation: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_atlas-vision-fLoc-task_desc-body-EBA_mask.nii.gz

parcel_name: vision-fLoc-task_body-EBA
parcel_type: mask
