# @package _global_

space: T1w
use_template_gm: False
gm_path: ./data/friends.fmriprep/sourcedata/smriprep/sub-*/anat/sub-*_label-GM_probseg.nii.gz

use_template_parcel: False
parcellation: ./atlas/tpl-sub*T1w/tpl-sub*T1w_res-anat_atlas-language-Toneva_desc-8_dseg.nii.gz

parcel_name: language-Toneva_8ROIs
parcel_type: dseg
