# @package _global_

space: MNI152NLin2009cAsym
use_template_gm: True
gm_path: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_label-GM_probseg.nii.gz

use_template_parcel: True
parcellation: ./atlas/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-func_atlas-language-Toneva_desc-8_dseg.nii.gz

parcel_name: language-Toneva_8ROIs
parcel_type: dseg
