# @package _global_

template: MNI152NLin2009cAsym
template_gm_path: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_label-GM_probseg.nii.gz
n_iter: 2

template_parcellation: ./atlases/tpl-MNI152NLin2009bAsym/tpl-MNI152NLin2009bAsym_res-03_atlas-BASC_desc-444_dseg.nii.gz
parcel_name: atlas-MIST_desc-444_dseg
parcel_type: dseg
