# @package _global_

space: T1w
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_label-GM_desc-fromFS_dseg.nii.gz

parcel_type: mask
use_template_parcel: False
parcellation: ./atlases/tpl-sub*T1w/tpl-sub*T1w_res-func_atlas-retinoVisionNpythy_label-V1_mask.nii.gz

parcel_name: retinoVisionNpythy
desc: V1
