# @package _global_

space: MNI152NLin2009cAsym
use_template_gm: False
resample_gm: False
gm_path: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_sub-*_res-func_label-GM_desc-fromFS_dseg.nii.gz

parcel_type: dseg
use_template_parcel: False
parcellation: ./atlases/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_sub-*_res-func_atlas-Ward_desc-10k_dseg.nii.gz

parcel_name: Ward
desc: 10k
